FROM nginx:alpine
# We add a Meta tag so the browser knows how to read the Emoji!
RUN echo '<html><head><meta charset="UTF-8"></head><body><h1>Day 23: Favour’s Secure Infrastructure 🦾</h1></body></html>' > /usr/share/nginx/html/index.html